### ISSUE TITLE
Playground broken - everything evaluates to "No Errors"

### ISSUE THREAD

**Issue by sascha-egerer** [phpstan/playground#20]
Looks like the playground is currently broken and everything evaluated to "No Errors" currently.

1. Open: https://phpstan.org/r/91b25bdf-b432-482b-8eea-1f81eea155b5
2. Looks good
<img width="1155" alt="Bildschirmfoto 2020-02-24 um 17 06 20" src="https://user-images.githubusercontent.com/1651414/75169012-1cb2a700-5728-11ea-941d-f733b5333aa8.png">
3. Click on analyse button
4. "No Errors"
<img width="1152" alt="Bildschirmfoto 2020-02-24 um 17 06 25" src="https://user-images.githubusercontent.com/1651414/75169043-263c0f00-5728-11ea-8450-e5575dc79bc5.png">

**Comment by ondrejmirtes** [comment]
Thank you, fixed: https://github.com/phpstan/phpstan/commit/bbfa6ac07df01d8d7de0f8b9033ecfb233706a56

Please note that even "Reflection Error: AnonymousClassXYZ not found" is not representative (PHPStan locally behaves differently), but that's because the playground currently uses static reflection that's under development. But most usual issues should be reported the same.

**Comment by sascha-egerer** [comment]
> Please note that even "Reflection Error: AnonymousClassXYZ not found" is not representative (PHPStan locally behaves differently), but that's because the playground currently uses static reflection that's under development. But most usual issues should be reported the same.

I've just used a link from another Ticket ;-)
Thank you for the fix!
